
name: Day-3 Docker Build, Scan & Push

on:
  workflow_run:
    workflows: ["CI Pipeline"]   # Must match the name in ci.yml
    types:
      - completed

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      - name: Create Dockerfile
        run: |
          echo 'FROM eclipse-temurin:17-jdk' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY *.jar app.jar' >> Dockerfile
          echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile

      - name: Login to Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REPO }}   # trial3pps5e.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}/docker-trial/expense-app:1.0 .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_REPO }}/docker-trial/expense-app:1.0
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REPO }}/docker-trial/expense-app:1.0
