name: Docker Build & Push

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/
          run-id: ${{ github.event.workflow_run.run_id }}   # <-- important fix

      - name: Verify jar exists
        run: ls -R build

      - name: Login to Artifactory Docker
        run: |
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | docker login ${{ secrets.DOCKER_REPO }} -u ${{ secrets.ARTIFACTORY_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REPO }}/docker-trial/spring-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}/docker-trial/spring-app:latest
