
name: Day-3 Docker Build, Scan & Push

on:
  push:
    branches:
      - master

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Create Dockerfile dynamically
      - name: Create Dockerfile
        run: |
          echo 'FROM eclipse-temurin:17-jdk' > Dockerfile
          echo 'WORKDIR /app' >> Dockerfile
          echo 'COPY target/*.jar app.jar' >> Dockerfile
          echo 'ENTRYPOINT ["java", "-jar", "app.jar"]' >> Dockerfile

      # Step 4: Login to JFrog Artifactory Docker Registry
      - name: Login to Artifactory
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_REPO }}   # trial3pps5e.jfrog.io
          username: ${{ secrets.ARTIFACTORY_USERNAME }}
          password: ${{ secrets.ARTIFACTORY_PASSWORD }}

      # Step 5: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REPO }}/docker-trial/expense-app:1.0 .

      # Step 6: Trivy Image Scan
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKER_REPO }}/docker-trial/expense-app:1.0
          format: table
          exit-code: 1
          severity: HIGH,CRITICAL

      # Step 7: Push Docker Image to JFrog
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REPO }}/docker-trial/expense-app:1.0
