name: Docker Build & Push

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]

permissions:
  contents: read
  actions: read        # required to download artifact
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifact from CI
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/
          run-id: ${{ github.event.workflow_run.id }}   # <-- changed (id not run_id)

      - name: Verify files
        run: ls -R build

      - name: Docker Login
        run: |
          echo "${{ secrets.ARTIFACTORY_PASSWORD }}" | \
          docker login ${{ secrets.DOCKER_REPO }} \
          -u "${{ secrets.ARTIFACTORY_USERNAME }}" --password-stdin

      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_REPO }}/docker-trial/spring-app:latest .

      - name: Push image
        run: docker push ${{ secrets.DOCKER_REPO }}/docker-trial/spring-app:latest
